export const Colors = {
  BLUE_PRIMARY_LIGHTER: '#2673CE',
  BLUE_SECONDARY_LIGHTER: '#3C93F9',
  BLUE_SOFT_LIGHTER: '#D4E3F5',

  ORANGE_PRIMARY_LIGHTER: '#F9C33C',
  ORANGE_SECONDARY_LIGHTER: '#FF981E',

  MAIN_TEXT_LIGHTER: '#09192D',
  MAIN_TEXT_TITLE_LIGHTER: '#2673CE',
}